accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: karan
    coins: ["20000token", "200000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: karan
  coins: ["5token", "100000stake"]
