name: contract-ci

on:
  pull_request:
  push:
    tags:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker compose
        run: STAKE_TOKEN="uraptorx" docker-compose up -d
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'Karan-3108/raptornamer'
          ref: 'v0.1.0-alpha'
      - name: Run deploy script
        run: |
          chmod a+x ./scripts/deploy_ci.sh
          ./scripts/deploy_ci.sh

